/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cicInterface;

import static cicInterface.PendingClaimsPage.ClassIndex;
import static cicInterface.PendingClaimsPage.UnclassifiedClaims;
import static cicSrc.Application.claimant1;
import static cicSrc.Application.claimant2;
import static cicSrc.Application.claimant3;
import static cicSrc.Application.Simple;
import static cicSrc.Application.Complex;
import static cicInterface.FormPage.NewSimpleForms;
import static cicInterface.FormPage.NewComplexForms;

/**
 *
 * @author george
 */
public class ClassifyClaimsPage extends javax.swing.JFrame {

    /**
     * Creates new form ClassifyClaimsPage
     */
    public ClassifyClaimsPage() {
        initComponents();
        if (ClassIndex>0){
            this.NoClaims_Label.setVisible(false);
            for(int i=0;i<ClassIndex;i++){
                
                
                     jTable1.getModel().setValueAt(UnclassifiedClaims[i].claim_ID, i, 0); // ID
                     jTable1.getModel().setValueAt(UnclassifiedClaims[i].claimantName, i, 1); // Name
                     jTable1.getModel().setValueAt(UnclassifiedClaims[i].claimantSurname, i, 2); // Surname
                     jTable1.getModel().setValueAt(UnclassifiedClaims[i].claimCostOfDmg, i, 3); // Location
                     if ((UnclassifiedClaims[i].claimantName==claimant1.name)&&(UnclassifiedClaims[i].claimantSurname==claimant1.surname))
                     {
                         jTable1.getModel().setValueAt(claimant1.priceOfCar, i, 4);
                
                     }
                     else if((UnclassifiedClaims[i].claimantName==claimant2.name)&&(UnclassifiedClaims[i].claimantSurname==claimant2.surname))
                     {
                         jTable1.getModel().setValueAt(claimant2.priceOfCar, i, 4);
                     }
                     else if((UnclassifiedClaims[i].claimantName==claimant3.name)&&(UnclassifiedClaims[i].claimantSurname==claimant3.surname))
                     {
                         jTable1.getModel().setValueAt(claimant3.priceOfCar, i, 4);
                     }
                     else
                     {
                          jTable1.getModel().setValueAt("Price of car unspecified!", i, 4);
                     }
                         
            
            }
        
        
        }
        else 
        {
            this.NoClaims_Label.setVisible(true);
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        SimpleProceed_Button = new javax.swing.JButton();
        ComplexProceed_Button = new javax.swing.JButton();
        NoClaims_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Claim ID", "Name", "Surname", "Cost Of Damage", "Price Of Car", "Simple", "Complex", "Form"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setRowHeight(22);
        jScrollPane1.setViewportView(jTable1);

        SimpleProceed_Button.setText("Proceed");
        SimpleProceed_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpleProceed_ButtonActionPerformed(evt);
            }
        });

        ComplexProceed_Button.setText("Proceed");
        ComplexProceed_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComplexProceed_ButtonActionPerformed(evt);
            }
        });

        NoClaims_Label.setText("There are no claims for classification! ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SimpleProceed_Button)
                        .addGap(73, 73, 73)
                        .addComponent(ComplexProceed_Button)
                        .addGap(186, 186, 186))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 87, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(NoClaims_Label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(NoClaims_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SimpleProceed_Button)
                    .addComponent(ComplexProceed_Button))
                .addGap(76, 76, 76))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SimpleProceed_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpleProceed_ButtonActionPerformed
        for (int i=0;i<4;i++){
            if ((Boolean)this.jTable1.getModel().getValueAt(i, 5)==true){
                UnclassifiedClaims[i].claimCategory="Simple";
                Simple[i]=true;
                this.jTable1.getModel().setValueAt("Simple form created!",i, 7);
                NewSimpleForms++;
                
                
            
            }   
            else if((Boolean)this.jTable1.getModel().getValueAt(i, 6)==true){
                UnclassifiedClaims[i].claimCategory="Complex";
                Complex[i]=true;
                this.jTable1.getModel().setValueAt("Complex form created!",i, 7);
                NewComplexForms++;
                
                
            }
           
        }
    }//GEN-LAST:event_SimpleProceed_ButtonActionPerformed

    private void ComplexProceed_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComplexProceed_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComplexProceed_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClassifyClaimsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClassifyClaimsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClassifyClaimsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClassifyClaimsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClassifyClaimsPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ComplexProceed_Button;
    private javax.swing.JLabel NoClaims_Label;
    private javax.swing.JButton SimpleProceed_Button;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
