/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cicInterface;


import static cicSrc.Application.claimant1;
import static cicSrc.Application.claimant2;
import static cicSrc.Application.claimant3;
import static cicSrc.Application.Simple;
import static cicSrc.Application.Complex;
import static cicInterface.FormPage.NewSimpleForms;
import static cicInterface.FormPage.NewComplexForms;
import static cicSrc.Application.ClaimsForClassification;
import static cicSrc.Application.unclassifiedClaims;
import static cicSrc.Application.unclassifiedIndex;
import static cicSrc.Application.complexClaims;
import static cicSrc.Application.complexIndex;
import static cicSrc.Application.simpleClaims;
import static cicSrc.Application.simpleIndex;

/**
 *
 * @author george
 */
public class ClassifyClaimsPage extends javax.swing.JFrame {

    /**
     * Creates new form ClassifyClaimsPage
     */
    
    public static int classifyFirst=0;
    
    public ClassifyClaimsPage() {
        initComponents();
        int j=classifyFirst;

        

        
        for (int k=0;k<4;k++){
            this.jTable1.getModel().setValueAt(false,k, 5);
            this.jTable1.getModel().setValueAt(false,k, 6);
        }
        if (ClaimsForClassification>0){

            this.NoClaims_Label.setVisible(false);
            for(int i=0;i<ClaimsForClassification;i++){
                
                
                     jTable1.getModel().setValueAt(unclassifiedClaims[j].claim_ID, i, 0); // ID
                     jTable1.getModel().setValueAt(unclassifiedClaims[j].claimantName, i, 1); // Name
                     jTable1.getModel().setValueAt(unclassifiedClaims[j].claimantSurname, i, 2); // Surname
                     jTable1.getModel().setValueAt(unclassifiedClaims[j].claimCostOfDmg, i, 3); // Location
                     if ((unclassifiedClaims[j].claimantName.equals(claimant1.name))&&(unclassifiedClaims[j].claimantSurname.equals(claimant1.surname)))
                     {
                         jTable1.getModel().setValueAt(claimant1.priceOfCar, i, 4);
                
                     }
                     else if((unclassifiedClaims[j].claimantName.equals(claimant2.name))&&(unclassifiedClaims[j].claimantSurname.equals(claimant2.surname)))
                     {
                         jTable1.getModel().setValueAt(claimant2.priceOfCar, i, 4);
                     }
                     else if((unclassifiedClaims[j].claimantName.equals(claimant3.name))&&(unclassifiedClaims[j].claimantSurname.equals(claimant3.surname)))
                     {
                         jTable1.getModel().setValueAt(claimant3.priceOfCar, i, 4);
                     }
                     else
                     {
                          jTable1.getModel().setValueAt("Price of car unspecified!", i, 4);
                     }
                     j++;    
            
            }

            
            
        }
        else 
        {
            this.NoClaims_Label.setVisible(true);
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Proceed_Button = new javax.swing.JButton();
        NoClaims_Label = new javax.swing.JLabel();
        BackToPage_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Claim ID", "Name", "Surname", "Cost Of Damage", "Price Of Car", "Simple", "Complex", "Form"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setRowHeight(22);
        jScrollPane1.setViewportView(jTable1);

        Proceed_Button.setText("Proceed");
        Proceed_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Proceed_ButtonActionPerformed(evt);
            }
        });

        NoClaims_Label.setText("There are no claims for classification! ");

        BackToPage_Button.setText("Back To Page");
        BackToPage_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToPage_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(NoClaims_Label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Proceed_Button)
                        .addGap(271, 271, 271))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BackToPage_Button)
                        .addGap(76, 76, 76))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(NoClaims_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Proceed_Button)
                .addGap(18, 18, 18)
                .addComponent(BackToPage_Button)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Proceed_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Proceed_ButtonActionPerformed
        int j=classifyFirst;
        
        for (int i=0;i<ClaimsForClassification;i++){
            if (((Boolean)this.jTable1.getModel().getValueAt(i, 5)==true) && ((Boolean)this.jTable1.getModel().getValueAt(i, 6)!=true)){
                unclassifiedClaims[j].claimCategory="Simple";
                Simple[i]=true;
                
                simpleClaims[simpleIndex]=unclassifiedClaims[j];
                simpleIndex++;
                this.jTable1.getModel().setValueAt("Simple form created!",i, 7);
                NewSimpleForms++;
                
                
            
            }   
            else if(((Boolean)this.jTable1.getModel().getValueAt(i, 6)==true) && ((Boolean)this.jTable1.getModel().getValueAt(i, 5)!=true)){
                unclassifiedClaims[j].claimCategory="Complex";
                Complex[i]=true;
                complexClaims[complexIndex]=unclassifiedClaims[j];
                complexIndex++;
                this.jTable1.getModel().setValueAt("Complex form created!",i, 7);
                NewComplexForms++;
                
                
            }
            j++;
           
        }
        classifyFirst=j;
        ClaimsForClassification=0;
        
    }//GEN-LAST:event_Proceed_ButtonActionPerformed

    private void BackToPage_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToPage_ButtonActionPerformed
        // TODO add your handling code here:
        PendingClaimsPage pending=new PendingClaimsPage();
        pending.setVisible(true);
    }//GEN-LAST:event_BackToPage_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClassifyClaimsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClassifyClaimsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClassifyClaimsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClassifyClaimsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClassifyClaimsPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToPage_Button;
    private javax.swing.JLabel NoClaims_Label;
    private javax.swing.JButton Proceed_Button;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
