/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cicInterface;

/**
 *
 * @author george
 */
public class FinanceDeptEmployeePage extends javax.swing.JFrame {

    /**
     * Creates new form FinanceEmployeePage
     */
    public FinanceDeptEmployeePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        PaymentRecords_MenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Inbox_MenuItem = new javax.swing.JMenuItem();
        ContactCDEmployee_MenuItem = new javax.swing.JMenuItem();
        ContactGarage_MenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        PendingClaims_MenuItem = new javax.swing.JMenuItem();
        ApprovedForPayment_MenuItem = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        Logout_MenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Payments");

        PaymentRecords_MenuItem.setText("Records");
        PaymentRecords_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentRecords_MenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(PaymentRecords_MenuItem);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Messages");

        Inbox_MenuItem.setText("Inbox");
        Inbox_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inbox_MenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(Inbox_MenuItem);

        ContactCDEmployee_MenuItem.setText("Contact EmployeeOfCD");
        ContactCDEmployee_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactCDEmployee_MenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(ContactCDEmployee_MenuItem);

        ContactGarage_MenuItem.setText("Contact GarageOwner");
        ContactGarage_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactGarage_MenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(ContactGarage_MenuItem);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Claims");

        PendingClaims_MenuItem.setText("Pending Claims");
        PendingClaims_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PendingClaims_MenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(PendingClaims_MenuItem);

        ApprovedForPayment_MenuItem.setText("Approved for Payment");
        ApprovedForPayment_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApprovedForPayment_MenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(ApprovedForPayment_MenuItem);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Logged");

        Logout_MenuItem.setText("Logout");
        Logout_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_MenuItemActionPerformed(evt);
            }
        });
        jMenu4.add(Logout_MenuItem);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PendingClaims_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PendingClaims_MenuItemActionPerformed
        PendingClaimsPage pendingPage=new PendingClaimsPage();
                pendingPage.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_PendingClaims_MenuItemActionPerformed

    private void PaymentRecords_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentRecords_MenuItemActionPerformed
        PaymentRecordsPage paymentRecordsPage=new PaymentRecordsPage();
                paymentRecordsPage.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_PaymentRecords_MenuItemActionPerformed

    private void Inbox_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inbox_MenuItemActionPerformed
        FinanceDeptEmployeeInboxPage financeEmployeeInboxPage=new FinanceDeptEmployeeInboxPage();
                financeEmployeeInboxPage.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_Inbox_MenuItemActionPerformed

    private void ContactCDEmployee_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactCDEmployee_MenuItemActionPerformed
        FinanceDeptEmployeeOutboxPage financeEmployeeOutboxPage=new FinanceDeptEmployeeOutboxPage();
                financeEmployeeOutboxPage.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_ContactCDEmployee_MenuItemActionPerformed

    private void ContactGarage_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactGarage_MenuItemActionPerformed
        FinanceDeptEmployeeOutboxPage financeEmployeeOutboxPage=new FinanceDeptEmployeeOutboxPage();
                financeEmployeeOutboxPage.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_ContactGarage_MenuItemActionPerformed

    private void ApprovedForPayment_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApprovedForPayment_MenuItemActionPerformed
        ClaimsApprovedForPaymentPage approvedClaimsPage=new ClaimsApprovedForPaymentPage();
                approvedClaimsPage.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_ApprovedForPayment_MenuItemActionPerformed

    private void Logout_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_MenuItemActionPerformed
        LoginPage loginPage=new LoginPage();
                loginPage.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_Logout_MenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinanceDeptEmployeePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinanceDeptEmployeePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinanceDeptEmployeePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinanceDeptEmployeePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinanceDeptEmployeePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ApprovedForPayment_MenuItem;
    private javax.swing.JMenuItem ContactCDEmployee_MenuItem;
    private javax.swing.JMenuItem ContactGarage_MenuItem;
    private javax.swing.JMenuItem Inbox_MenuItem;
    private javax.swing.JMenuItem Logout_MenuItem;
    private javax.swing.JMenuItem PaymentRecords_MenuItem;
    private javax.swing.JMenuItem PendingClaims_MenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
