/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cicInterface;

import static cicSrc.Application.classifiedClaims;
import static cicSrc.Application.classifiedFirst;

/**
 *
 * @author george
 */
public class FormPage extends javax.swing.JFrame {

    /**
     * Creates new form FillInFormPage
     */
    //public static int NewSimpleForms=0;
    //public static int NewComplexForms=0;
    public static int NewForms=0;
    
    public static String formStatus="formNotCreated";
    
    public FormPage() {
        initComponents();
        
        int j=classifiedFirst;
        
        for (int k=0;k<4;k++){
            this.jTable1.getModel().setValueAt(false,k, 2);
            
        }
        
        if (NewForms>0){
            this.NoForms_Label.setVisible(false);
            this.NewFormsCreated_Label.setVisible(true);
            for (int i=0;i<NewForms;i++){
                jTable1.getModel().setValueAt(classifiedClaims[j].claim_ID, i, 0); // ID
                jTable1.getModel().setValueAt(classifiedClaims[j].claimCategory, i, 1);
            
            }
        
        }
        
        this.ClaimID_Label.setVisible(false);
        this.ClaimID_TextFIled.setVisible(false);
        this.Name_Label.setVisible(false);
        this.ToBeFilledInName_TextField.setVisible(false);
        this.ToBeCheckedName_TextField.setVisible(false);
        this.Surname_Label.setVisible(false);
        this.ToBeFilledInSurname_TextField.setVisible(false);
        this.ToBeCheckedSurname_TextField.setVisible(false);
        this.Date_Label.setVisible(false);
        this.ToBeFilledInDate_TextField.setVisible(false);
        this.ToBeCheckedDate_TextField.setVisible(false);
        this.Location_Label.setVisible(false);
        this.ToBeFilledInLocation_TextField.setVisible(false);
        this.ToBeCheckedLocation_TextField.setVisible(false);
        this.Plate_Label.setVisible(false);
        this.ToBeFilledInPlate_TextField.setVisible(false);
        this.ToBeCheckedPlate_TextField.setVisible(false);
        this.Agreement_Label.setVisible(false);
        this.Agree_CheckBox.setVisible(false);
        this.SubmitForm_Button.setVisible(false);
        this.NotFilledInCorrectly_Button.setVisible(false);
        this.RegisterClaim_Button.setVisible(false);
        
        
        LoginPage log = new LoginPage();
        
        if (log.userRole == "Claimant"){
            
        
        
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NoForms_Label = new javax.swing.JLabel();
        ToBeFilledInName_TextField = new javax.swing.JTextField();
        ToBeFilledInSurname_TextField = new javax.swing.JTextField();
        ToBeFilledInLocation_TextField = new javax.swing.JTextField();
        ToBeFilledInDate_TextField = new javax.swing.JTextField();
        ToBeFilledInPlate_TextField = new javax.swing.JTextField();
        Name_Label = new javax.swing.JLabel();
        Surname_Label = new javax.swing.JLabel();
        Date_Label = new javax.swing.JLabel();
        Location_Label = new javax.swing.JLabel();
        Plate_Label = new javax.swing.JLabel();
        Agreement_Label = new javax.swing.JLabel();
        Agree_CheckBox = new javax.swing.JCheckBox();
        SubmitForm_Button = new javax.swing.JButton();
        BackToPage_Button = new javax.swing.JButton();
        NotFilledInCorrectly_Button = new javax.swing.JButton();
        RegisterClaim_Button = new javax.swing.JButton();
        NewFormsCreated_Label = new javax.swing.JLabel();
        ClaimID_TextFIled = new javax.swing.JTextField();
        ClaimID_Label = new javax.swing.JLabel();
        ToBeCheckedName_TextField = new javax.swing.JTextField();
        ToBeCheckedSurname_TextField = new javax.swing.JTextField();
        ToBeCheckedDate_TextField = new javax.swing.JTextField();
        ToBeCheckedLocation_TextField = new javax.swing.JTextField();
        ToBeCheckedPlate_TextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        FillInForm_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NoForms_Label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NoForms_Label.setForeground(new java.awt.Color(204, 0, 0));
        NoForms_Label.setText("No forms created!");

        ToBeFilledInSurname_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToBeFilledInSurname_TextFieldActionPerformed(evt);
            }
        });

        ToBeFilledInLocation_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToBeFilledInLocation_TextFieldActionPerformed(evt);
            }
        });

        ToBeFilledInDate_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToBeFilledInDate_TextFieldActionPerformed(evt);
            }
        });

        ToBeFilledInPlate_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToBeFilledInPlate_TextFieldActionPerformed(evt);
            }
        });

        Name_Label.setText("Name");

        Surname_Label.setText("Surname");

        Date_Label.setText("Date Of Accident");

        Location_Label.setText("Location Of Accident");

        Plate_Label.setText("Plate Number");

        Agreement_Label.setText("Do you agree with a 5% increase on your monthly installments?");

        Agree_CheckBox.setText("Yes");

        SubmitForm_Button.setText("Submit");

        BackToPage_Button.setText("Back To Page");
        BackToPage_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToPage_ButtonActionPerformed(evt);
            }
        });

        NotFilledInCorrectly_Button.setText("Not filled in correctly!");

        RegisterClaim_Button.setText("Register Claim");

        NewFormsCreated_Label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NewFormsCreated_Label.setText("New forms created!");

        ClaimID_TextFIled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClaimID_TextFIledActionPerformed(evt);
            }
        });

        ClaimID_Label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ClaimID_Label.setText("Claim ID");

        ToBeCheckedName_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToBeCheckedName_TextFieldActionPerformed(evt);
            }
        });

        ToBeCheckedSurname_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToBeCheckedSurname_TextFieldActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Claim ID ", "Category", "Select Claim"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        FillInForm_Button.setText("Fill In Form");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackToPage_Button)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Name_Label)
                                    .addGap(96, 96, 96))
                                .addComponent(Surname_Label, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Date_Label, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(ClaimID_Label))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ToBeFilledInPlate_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ToBeCheckedPlate_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ToBeFilledInLocation_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ToBeCheckedLocation_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ToBeFilledInDate_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ToBeCheckedDate_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ToBeFilledInName_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ToBeFilledInSurname_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ToBeCheckedName_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ToBeCheckedSurname_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(ClaimID_TextFIled, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 426, Short.MAX_VALUE)
                        .addComponent(NoForms_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Plate_Label)
                            .addComponent(Location_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(NotFilledInCorrectly_Button)
                                        .addGap(18, 18, 18)
                                        .addComponent(RegisterClaim_Button))
                                    .addComponent(Agreement_Label))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SubmitForm_Button)
                                    .addComponent(Agree_CheckBox)))
                            .addComponent(NewFormsCreated_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(FillInForm_Button)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(NewFormsCreated_Label)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FillInForm_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClaimID_TextFIled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClaimID_Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ToBeFilledInName_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Name_Label)
                    .addComponent(ToBeCheckedName_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoForms_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ToBeFilledInSurname_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Surname_Label)
                    .addComponent(ToBeCheckedSurname_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ToBeFilledInDate_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Date_Label)
                    .addComponent(ToBeCheckedDate_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ToBeFilledInLocation_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Location_Label)
                    .addComponent(ToBeCheckedLocation_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Plate_Label)
                    .addComponent(ToBeFilledInPlate_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ToBeCheckedPlate_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Agreement_Label)
                    .addComponent(Agree_CheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SubmitForm_Button)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NotFilledInCorrectly_Button)
                    .addComponent(RegisterClaim_Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BackToPage_Button)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ToBeFilledInDate_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToBeFilledInDate_TextFieldActionPerformed
        // TODO 
    }//GEN-LAST:event_ToBeFilledInDate_TextFieldActionPerformed

    private void ToBeFilledInPlate_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToBeFilledInPlate_TextFieldActionPerformed
        // TODO 
    }//GEN-LAST:event_ToBeFilledInPlate_TextFieldActionPerformed

    private void ToBeFilledInLocation_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToBeFilledInLocation_TextFieldActionPerformed
        // TODO 
    }//GEN-LAST:event_ToBeFilledInLocation_TextFieldActionPerformed

    private void ToBeFilledInSurname_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToBeFilledInSurname_TextFieldActionPerformed
        // TODO 
    }//GEN-LAST:event_ToBeFilledInSurname_TextFieldActionPerformed

    private void BackToPage_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToPage_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackToPage_ButtonActionPerformed

    private void ClaimID_TextFIledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClaimID_TextFIledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClaimID_TextFIledActionPerformed

    private void ToBeCheckedName_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToBeCheckedName_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToBeCheckedName_TextFieldActionPerformed

    private void ToBeCheckedSurname_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToBeCheckedSurname_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToBeCheckedSurname_TextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Agree_CheckBox;
    private javax.swing.JLabel Agreement_Label;
    private javax.swing.JButton BackToPage_Button;
    private javax.swing.JLabel ClaimID_Label;
    private javax.swing.JTextField ClaimID_TextFIled;
    private javax.swing.JLabel Date_Label;
    private javax.swing.JButton FillInForm_Button;
    private javax.swing.JLabel Location_Label;
    private javax.swing.JLabel Name_Label;
    private javax.swing.JLabel NewFormsCreated_Label;
    private javax.swing.JLabel NoForms_Label;
    private javax.swing.JButton NotFilledInCorrectly_Button;
    private javax.swing.JLabel Plate_Label;
    private javax.swing.JButton RegisterClaim_Button;
    private javax.swing.JButton SubmitForm_Button;
    private javax.swing.JLabel Surname_Label;
    private javax.swing.JTextField ToBeCheckedDate_TextField;
    private javax.swing.JTextField ToBeCheckedLocation_TextField;
    private javax.swing.JTextField ToBeCheckedName_TextField;
    private javax.swing.JTextField ToBeCheckedPlate_TextField;
    private javax.swing.JTextField ToBeCheckedSurname_TextField;
    private javax.swing.JTextField ToBeFilledInDate_TextField;
    private javax.swing.JTextField ToBeFilledInLocation_TextField;
    private javax.swing.JTextField ToBeFilledInName_TextField;
    private javax.swing.JTextField ToBeFilledInPlate_TextField;
    private javax.swing.JTextField ToBeFilledInSurname_TextField;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
