/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cicInterface;

import cicSrc.Application;


/**
 *
 * @author george
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public static boolean handlerA=false;
    
    public static String userRole;
    
    public LoginPage() {
        initComponents();
        Application.initialize();
        LoginFailed_Label.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        User_Text = new javax.swing.JTextField();
        Username_label = new javax.swing.JLabel();
        Password_Label = new javax.swing.JLabel();
        Password_Text = new javax.swing.JPasswordField();
        EmployeeOfCD_Button = new javax.swing.JButton();
        LoginFailed_Label = new javax.swing.JLabel();
        ClaimHandlerA_Button = new javax.swing.JButton();
        FinanceEmployee_Button = new javax.swing.JButton();
        Customer_Button = new javax.swing.JButton();
        Garage_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        User_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_TextActionPerformed(evt);
            }
        });

        Username_label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Username_label.setText("Username");

        Password_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Password_Label.setText("Password");

        EmployeeOfCD_Button.setText("LoginAsEmployeeOfCD");
        EmployeeOfCD_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeOfCD_ButtonActionPerformed(evt);
            }
        });

        LoginFailed_Label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LoginFailed_Label.setForeground(new java.awt.Color(255, 0, 0));
        LoginFailed_Label.setText("Login Failed!");

        ClaimHandlerA_Button.setText("LoginAsClaimHandlerA");
        ClaimHandlerA_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClaimHandlerA_ButtonActionPerformed(evt);
            }
        });

        FinanceEmployee_Button.setText("LoginAsFinanceEmployee");
        FinanceEmployee_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinanceEmployee_ButtonActionPerformed(evt);
            }
        });

        Customer_Button.setText("LoginAsCustomer");
        Customer_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Customer_ButtonActionPerformed(evt);
            }
        });

        Garage_Button.setText("LoginAsGarageOwner");
        Garage_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Garage_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EmployeeOfCD_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LoginFailed_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Password_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Username_label, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(User_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Password_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Garage_Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ClaimHandlerA_Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Customer_Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(24, 24, 24)
                                .addComponent(FinanceEmployee_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(32, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Username_label)
                    .addComponent(User_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password_Label)
                    .addComponent(Password_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployeeOfCD_Button)
                    .addComponent(Customer_Button))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LoginFailed_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ClaimHandlerA_Button)
                            .addComponent(FinanceEmployee_Button))
                        .addGap(18, 18, 18)
                        .addComponent(Garage_Button)
                        .addContainerGap(78, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void User_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_User_TextActionPerformed

    private void EmployeeOfCD_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeOfCD_ButtonActionPerformed
        String user = User_Text.getText();
        String pass = Password_Text.getText();
        
        if (user.equals(Application.employeeCD.username) && pass.equals(Application.employeeCD.password)){
            
            handlerA=false;
            userRole="EmployeeOfCD";
            EmployeeOfCDPage cdPage=new EmployeeOfCDPage();
                
                cdPage.setVisible(true);
                this.dispose();
            
            
        
        }
        else{
            
            
            LoginFailed_Label.setVisible(true);
        
        }
    }//GEN-LAST:event_EmployeeOfCD_ButtonActionPerformed

    private void ClaimHandlerA_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClaimHandlerA_ButtonActionPerformed
        String user = User_Text.getText();
        String pass = Password_Text.getText();
        
        if (user.equals(Application.claimHandlerA.username) && pass.equals(Application.claimHandlerA.password)){
            
            handlerA=true;
            userRole="ClaimHandlerA";
            EmployeeOfCDPage handlerAPage=new EmployeeOfCDPage();
                
                handlerAPage.setVisible(true);
                this.dispose();
            
            
        
        }
        else{
            
            
            LoginFailed_Label.setVisible(true);
        
        }
    }//GEN-LAST:event_ClaimHandlerA_ButtonActionPerformed

    private void FinanceEmployee_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinanceEmployee_ButtonActionPerformed
        String user = User_Text.getText();
        String pass = Password_Text.getText();
        
        if (user.equals(Application.financialDeptEmployee.username) && pass.equals(Application.financialDeptEmployee.password)){
            
            userRole="FinanceDeptEmployee";
            FinanceDeptEmployeePage financialDeptPage=new FinanceDeptEmployeePage();
                financialDeptPage.setVisible(true);
                this.dispose();
            
            
        
        }
        else{
            
            
            LoginFailed_Label.setVisible(true);
        
        }
    }//GEN-LAST:event_FinanceEmployee_ButtonActionPerformed

    private void Customer_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Customer_ButtonActionPerformed
        String user = User_Text.getText();
        String pass = Password_Text.getText();
        
        
        if (user.equals(Application.claimant1.username) && pass.equals(Application.claimant1.password)){
            
            userRole="Claimant";
            ClaimantPage claimantPage=new ClaimantPage();
                claimantPage.setVisible(true);
                this.dispose();
            
            
        
        }
        else{
            
            
            LoginFailed_Label.setVisible(true);
        
        }
    }//GEN-LAST:event_Customer_ButtonActionPerformed

    private void Garage_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Garage_ButtonActionPerformed
        String user = User_Text.getText();
        String pass = Password_Text.getText();
        
        if (user.equals(Application.garage1.username) && pass.equals(Application.garage1.password)){
            
            userRole="GarageOwner";
            GarageOwnerPage garagePage=new GarageOwnerPage();
                garagePage.setVisible(true);
                this.dispose();
            
            
        
        }
        else{
            
            
            LoginFailed_Label.setVisible(true);
        
        }
    }//GEN-LAST:event_Garage_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClaimHandlerA_Button;
    private javax.swing.JButton Customer_Button;
    private javax.swing.JButton EmployeeOfCD_Button;
    private javax.swing.JButton FinanceEmployee_Button;
    private javax.swing.JButton Garage_Button;
    private javax.swing.JLabel LoginFailed_Label;
    private javax.swing.JLabel Password_Label;
    private javax.swing.JPasswordField Password_Text;
    private javax.swing.JTextField User_Text;
    private javax.swing.JLabel Username_label;
    // End of variables declaration//GEN-END:variables
}
