/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cicInterface;

/**
 *
 * @author george
 */

import cicSrc.Claim;

public class PendingClaimsPage extends javax.swing.JFrame {

    /**
     * Creates new form PendingClaimsPage
     */
    
     //boolean variables checking when the positive button is pressed.
        boolean positive1=false;
        boolean positive2=false;
        boolean positive3=false;
        boolean positive4=false;
        
      public static Claim pendingClaim;
    
    //number of approved payments (is subject to change depending on the approved payments each time)
    public static int approved_payments = 0;
    
    public PendingClaimsPage() {
        initComponents();
        this.CheckInsurance_Button.setVisible(false);
        this.ClassifyClaim_Button.setVisible(false);
        this.DamageHistory_Button.setVisible(false);
        this.ContactGarage_Button.setVisible(false);
        this.MarkClaim_Button.setVisible(false);
        if (NewClaimsPage.pendingClaimsNumber>0){
            for (int i=0;i<NewClaimsPage.pendingClaimsNumber;i++){
                this.pendingClaims_Table.getModel().setValueAt((String)NewClaimsPage.pendingClaims[i], i, 0);
            
            
            }
            this.CheckInsurance_Button.setVisible(true);
        
        }
       
            
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackToPage = new javax.swing.JButton();
        CheckInsurance_Button = new javax.swing.JButton();
        ClassifyClaim_Button = new javax.swing.JButton();
        DamageHistory_Button = new javax.swing.JButton();
        ContactGarage_Button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pendingClaims_Table = new javax.swing.JTable();
        MarkClaim_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackToPage.setText("Back");
        BackToPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToPageActionPerformed(evt);
            }
        });

        CheckInsurance_Button.setText("Check Insurance");
        CheckInsurance_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckInsurance_ButtonActionPerformed(evt);
            }
        });

        ClassifyClaim_Button.setText("Classify Claim");
        ClassifyClaim_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassifyClaim_ButtonActionPerformed(evt);
            }
        });

        DamageHistory_Button.setText(" Damage History");
        DamageHistory_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DamageHistory_ButtonActionPerformed(evt);
            }
        });

        ContactGarage_Button.setText("Contact Garage");
        ContactGarage_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactGarage_ButtonActionPerformed(evt);
            }
        });

        pendingClaims_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Claims", "Insured", "Not Insured", "Simple", "Complex", "Damage History Checked", "Garage Owner Phoned", "Positive", "Negative", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        pendingClaims_Table.setPreferredSize(new java.awt.Dimension(750, 64));
        pendingClaims_Table.setRowHeight(22);
        jScrollPane1.setViewportView(pendingClaims_Table);

        MarkClaim_Button.setText("Mark Claim");
        MarkClaim_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarkClaim_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackToPage)
                .addGap(112, 112, 112))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(CheckInsurance_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(172, 172, 172)
                        .addComponent(ClassifyClaim_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addComponent(DamageHistory_Button)
                        .addGap(39, 39, 39)
                        .addComponent(ContactGarage_Button)
                        .addGap(103, 103, 103)
                        .addComponent(MarkClaim_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1552, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 187, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckInsurance_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ClassifyClaim_Button)
                    .addComponent(DamageHistory_Button)
                    .addComponent(ContactGarage_Button)
                    .addComponent(MarkClaim_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107)
                .addComponent(BackToPage)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
                  
        
    private void BackToPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToPageActionPerformed
        // TODO add your handling code here:
        
        LoginPage login = new LoginPage();
        if (login.userRole == "EmployeeOfCD")
        {
            EmployeeOfCDPage e = new EmployeeOfCDPage();
            e.setVisible(true);
            this.dispose();
        }
        
        else if (login.userRole == "ClaimHandlerA")
        {
            ClaimHandlerAPage c = new ClaimHandlerAPage();
            c.setVisible(true);
            this.dispose();
        }
        
        else if (login.userRole == "Claimant")
        {
            ClaimantPage p = new ClaimantPage();
            p.setVisible(true);
            this.dispose();
        }
        
        else if (login.userRole == "FinanceDeptEmployee")
        {
            FinanceDeptEmployeePage f = new FinanceDeptEmployeePage();
            f.setVisible(true);
            this.dispose();
        }
        
        else 
        {
            GarageOwnerPage g=new GarageOwnerPage();
            g.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_BackToPageActionPerformed

    private void ClassifyClaim_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassifyClaim_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClassifyClaim_ButtonActionPerformed

    private void ContactGarage_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactGarage_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactGarage_ButtonActionPerformed

    private void CheckInsurance_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckInsurance_ButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CheckInsurance_ButtonActionPerformed

    private void DamageHistory_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DamageHistory_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DamageHistory_ButtonActionPerformed

    private void MarkClaim_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarkClaim_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MarkClaim_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PendingClaimsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PendingClaimsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PendingClaimsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PendingClaimsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PendingClaimsPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToPage;
    private javax.swing.JButton CheckInsurance_Button;
    private javax.swing.JButton ClassifyClaim_Button;
    private javax.swing.JButton ContactGarage_Button;
    private javax.swing.JButton DamageHistory_Button;
    private javax.swing.JButton MarkClaim_Button;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable pendingClaims_Table;
    // End of variables declaration//GEN-END:variables
}
